spack:
  specs:
    - cli11
    # - "covfie@0.14:" #TODO: uncomment when upgrading spack
    - cmake
    - "geant4@11.0"
    - git
    - "googletest@1.10:"
    - hepmc3
      #- mpi #TODO: uncomment when upgrading
    - ninja
    - nlohmann-json
    - "python@3.6:"
  concretizer:
    unify: true
  compilers:
    - compiler:
        spec: rocmcc@=7.1.0
        paths:
          cc: /opt/rocm/llvm/bin/clang
          cxx: /opt/rocm/llvm/bin/clang++
          f77: /usr/bin/gfortran
          fc: /usr/bin/gfortran
        modules: []
        flags: {}
        operating_system: ubuntu24.04
        target: x86_64
  packages:
    rocrand:
      externals:
      - spec: rocrand@7.1.0
        prefix: /opt/rocm
    hiprand:
      externals:
      - spec: hiprand@7.1.0
        prefix: /opt/rocm
    rocthrust:
      externals:
      - spec: rocthrust@7.1.0
        prefix: /opt/rocm
    hipcub:
      externals:
      - spec: hipcub@7.1.0
        prefix: /opt/rocm
    all:
      target:
      - x86_64_v3
      # MI250x, see https://llvm.org/docs/AMDGPUUsage.html
      #variants: +rocm amdgpu_target=gfx90a cxxstd=17
      variants: cxxstd=17
      compiler: ["rocmcc@7.1.0"]
    root:
      variants: ~davix ~examples ~x ~opengl ~tbb ~rootfit ~python ~math ~gsl cxxstd=17
  config:
    install_tree: /opt/software
  view: /opt/view
